FROM ubuntu:20.04
ENV TZ=Europe/Paris
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt update && apt install -y build-essential vim cmake git wget tmux zlib1g zlib1g-dev libbz2-dev libffi-dev libreadline-dev libsqlite3-dev lzma  liblzma-dev libbz2-dev sudo libssl-dev libglib2.0-0 libgl1

# RUN useradd -ms /bin/bash -g root -G sudo dev
# RUN echo "dev:dev"|chpasswd

RUN useradd -u 1001 -ms /bin/bash -g  root -G sudo mitsuzaw
RUN echo "mitsuzaw:dev"| chpasswd

USER mitsuzaw
WORKDIR /home/mitsuzaw

# install pyenv
RUN git clone https://github.com/pyenv/pyenv.git ~/.pyenv
RUN echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
RUN echo 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
RUN echo 'eval "$(pyenv init -)"' >> ~/.bashrc


