detection_approaches = ["interpretable_mmd", "wasserstein_independence"]
# ram is the faster. flexible-file is slower, but less RAM-memory burden.
dataset_type_backend = "ram"

[base]
    file_name_sqlite3 = "exp_result.sqlite3"
    name_experiment_db = "experiment.json"

    # Rewriting the path here!
    path_experiment_root = "/home/kmitsuzawa/DATA/mitsuzaw/eurecom/mmd-two-sample-test-variable-selection/cat_and_dogs"
    dir_name_data = "data"
    dir_models = "models"
    dir_logs = "logs"

[computational_resource]
    # cpu or cuda
    train_accelerator = "cuda"

    distributed_mode = "single"
    dask_n_workers = 24
    dask_threads_per_worker = 1

[data_setting]
    target_image_size = [32, 32]

    data_mode = "cat_and_dogs"
    # comment: replace these following paths below. To the directory where your AFHQ dataset exist.
    path_dir_data_source_x = "/home/kmitsuzawa/DATA/mitsuzaw/animal_faces/data/afhq/train/cat"
    path_dir_data_source_y = "/home/kmitsuzawa/DATA/mitsuzaw/animal_faces/data/afhq/train/dog"
    file_extension = 'jpg'

    file_name_x = "x.pt"
    file_name_y = "y.pt"


[data_generation]
    sample_size_train = 200
    sample_size_test = 200



[mmd_baseline]
    devices = 'auto'
    MAX_EPOCH = 9999


[cv_selection]
    MAX_EPOCH = 9999
    candidate_regularization_parameter = 'auto'
    n_regularization_parameter = 5

    n_subsampling = 10
